APP = r'c:\Users\ahmed\pharmaAI\app.py'
with open(APP, encoding='utf-8-sig') as f:
    lines = f.readlines()

start = 362   # 0-based, line 363
end   = 423   # exclusive

new_block = (
    '    # 4. System prompt - simple narrative (structured numbered lists cause model to stop after 1-5 tokens)\n'
    '    if _is_clinical:\n'
    '        _SYS = (\n'
    '            "You are a Senior Clinical Pharmacist AI. "\n'
    '            "Give thorough, accurate clinical answers about drug interactions. "\n'
    '            "Match the language the user used (Arabic or English)."\n'
    '        ) + _rag_block\n'
    '    else:\n'
    '        _SYS = (\n'
    '            "You are a helpful Clinical Pharmacist AI assistant. "\n'
    '            "Respond politely and concisely. "\n'
    '            "Match the language the user used (Arabic or English)."\n'
    '        )\n'
    '\n'
    '    # 5. Build raw ChatML prompt\n'
    '    # client.chat() and generate(system=) trigger ChatML stop tokens on first token -- returns empty.\n'
    '    # generate(raw=True) + stop=None is the only reliable method for this model.\n'
    '    # Numbered section lists cause early stop; use free-form question instead.\n'
    '    if _is_clinical:\n'
    '        _user_msg = (\n'
    '            f"Tell me about this drug interaction or clinical case: {_msg}. "\n'
    '            "Cover the severity level (MAJOR/MODERATE/MINOR), the pharmacological mechanism, "\n'
    '            "the clinical effects on the patient, the management recommendations, "\n'
    '            "and the monitoring parameters."\n'
    '        )\n'
    '    else:\n'
    '        _user_msg = _msg\n'
    '\n'
    '    full_prompt = (\n'
    r'        f"<|im_start|>system\n{_SYS}\n<|im_end|>\n"' + '\n'
    r'        f"<|im_start|>user\n{_user_msg}\n<|im_end|>\n"' + '\n'
    r'        f"<|im_start|>assistant\n"' + '\n'
    '    )\n'
    '\n'
    '    # 6. Generate\n'
    '    try:\n'
    '        client = _ollama.Client(host=_HOST)\n'
    '        resp = client.generate(\n'
    '            model=_MODEL,\n'
    '            prompt=full_prompt,\n'
    '            raw=True,\n'
    '            options={\n'
    '                "num_predict": 1500,\n'
    '                "temperature": 0.2,\n'
    '                "top_p":       0.85,\n'
    '                "num_ctx":     2048,\n'
    '                "num_gpu":     20,\n'
    '                "stop":        None,\n'
    '            },\n'
    '        )\n'
    '        answer = resp.response.strip()\n'
    '\n'
    '        if len(answer) < 15:\n'
    '            return "\u26a0\ufe0f \u0644\u0645 \u064a\u0635\u062f\u0631 \u0627\u0644\u0645\u0648\u062f\u064a\u0644 \u0631\u062f\u0627\u064b. \u062a\u0623\u0643\u062f \u0645\u0646 \u062a\u0634\u063a\u064a\u0644 Ollama \u0648\u0623\u0639\u062f \u0627\u0644\u0645\u062d\u0627\u0648\u0644\u0629."\n'
    '\n'
    '        if rag_chunks and rag_chunks[0].get("score", 0) >= 0.65:\n'
    '            from rag_engine import format_citations\n'
    '            answer += f"\\n\\n---\\n{format_citations(rag_chunks)}"\n'
    '\n'
    '        return answer\n'
)

replaced = lines[:start] + [new_block] + lines[end:]
with open(APP, 'w', encoding='utf-8') as f:
    f.writelines(replaced)
print('Patch applied, total lines:', len(replaced))
